### ISSUE TITLE
Lavalink.py generates errors when it receives messages from the Lavalink server

### ISSUE THREAD

**Issue by maxsspeaker** [Devoxin/Lavalink.py#153]
### Summary
Over time, errors begin to appear in the logs, some people complain that their player is broken

### Lavalink & System Version
Arch Linux ARM last verison on 31.12.2024
python 3.12
Lavalink.py 5.9.0
Lavalink 4.0.8
- youtube-source 1.11.2

### Reproduction
at a random moment an error begins to appear in the logs related to receiving data from the Lavalink server, although now it has turned into spam

### Expected Results
The error should not occur, or some explanation for this situation

### Actual Results
[Node:maxsspeaker-node] Unexpected error occurred whilst processing websocket message
Traceback (most recent call last):
  File "/home/maxsspeaker/.local/lib/python3.12/site-packages/lavalink/transport.py", line 230, in _handle_message_safe
    await self._handle_message(msg.json())
  File "/home/maxsspeaker/.local/lib/python3.12/site-packages/lavalink/transport.py", line 274, in _handle_message
    await self._handle_event(data)
  File "/home/maxsspeaker/.local/lib/python3.12/site-packages/lavalink/transport.py", line 303, in _handle_event
    assert player.current is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

### Checklist
- [+] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [+] Have you checked that your Lavalink password isn't visible?
- [+] Have you given a traceback if possible?

![изображение](https://github.com/user-attachments/assets/6374eee8-8435-4810-af5f-bf6a7131c3f3)

**Comment by devoxin** [comment]
Are you calling player.skip() multiple times in a row?

**Comment by maxsspeaker** [comment]
no, I use my own code, where next is used instead of skip, in the code, it is implemented as "player.stop" and then "player.play(AudioTreak)", but such errors begin to occur when the player is running for a very long time without interruption

Edit: 
Sorry for the confusion, I'm on my computer now, I'm just executing the command "player.play(AudioTreak)" without using player.stop

**Comment by devoxin** [comment]
There is a known issue where many calls to `player.play()` in quick succession can cause this issue but I've not heard of this issue occurring under any other conditions

**Comment by maxsspeaker** [comment]
Any ideas on how I can fix this problem? Since at the moment, the bot plays music correctly, but these errors appear over time
